name: Sync All Project Scripts

on:
  schedule:
    - cron: '0 0 */7 * *' # Runs every 7 days
  workflow_dispatch: # Allows manual trigger

jobs:
  project1_sync:
    uses: TyRadman/central-workflows/.github/workflows/scripts_syncer.yml@main
    with:
      project_repo: "TyRadman/Tanklike"
      scripts_repo: "TyRadman/tanklike-scripts"
      source_folder: "Assets/_Code"
